"""add language to posts

Revision ID: 686aad3bc7c4
Revises: e66a0986ec80
Create Date: 2019-03-04 13:29:30.247303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686aad3bc7c4'
down_revision = 'e66a0986ec80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'language')
    # ### end Alembic commands ###
